// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sltqeropgwbkwshpjepo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsdHFlcm9wZ3dia3dzaHBqZXBvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMDQ5MzcsImV4cCI6MjA2ODU4MDkzN30.elQ6y_PTaGrsh0Gp6LvJohsvERnLR4a4ZaFaCtPidao";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});